language: node_js
node_js:
  - 0.12
sudo: false
before_install: npm install -g grunt-cli
install:
  - npm install justo-task-result
  - npm install
#before_script:
#script:
#after_success:
#after_failure:
#after_script:
